<a href="https://colab.research.google.com/github/suvyakthamedavarapu-hub/3SKILL-Projects/blob/main/Project_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Medavarapu Suvyaktha

Project 2 (3SKILL)

Title: AI-Based Hiring Prediction System

 (End-to-End Machine Learning Project)

Project Objective:

To build an AI-based Hiring Prediction System using a resume screening dataset.

The goal is to develop a Machine Learning model that predicts whether a candidate will be:
• Hired (1)
• Rejected (0)

Based on resume information such as skills, experience, education, certifications, projects, and salary expectations.

Pre-Step: Uploaded Files into Google Colab

In [2]:
from google.colab import files
uploaded = files.upload()

Saving AI-Based Hiring Prediction System.csv to AI-Based Hiring Prediction System (1).csv

Task - 1: Load and Understand the Dataset

Step - 1: Imported required Libraries to perform the operations

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

Step - 2: Loading the dataset

In [4]:
df = pd.read_csv('AI-Based Hiring Prediction System.csv')

Step - 3: Display the Primary Data

In [5]:
df.head()
df.tail()
df.sample(5)

,Resume_ID,Name,Skills,Experience (Years),Education,Certifications,Job Role,Recruiter Decision,Salary Expectation ($),Projects Count,AI Score (0-100)
566,567,Julie Thompson,"C++, Java, React, SQL",9,MBA,AWS Certified,Software Engineer,Hire,81897,4,100
510,511,Roger Lewis,"Networking, Ethical Hacking, Linux, Cybersecurity",9,B.Tech,Deep Learning Specialization,Cybersecurity Analyst,Hire,80779,5,100
277,278,Dwayne Taylor,"React, C++, SQL, Java",4,B.Tech,Deep Learning Specialization,Software Engineer,Hire,90345,7,100
465,466,Jessica Trevino,"TensorFlow, Pytorch, Python, NLP",4,MBA,AWS Certified,AI Researcher,Hire,61757,2,80
716,717,Marissa Cook,"C++, SQL, React, Java",8,PhD,Deep Learning Specialization,Software Engineer,Hire,100202,5,100

Step - 4: [Q & A]

Question 1: What type of data is present?

Answer: The dataset contains both structured and unstructured data related to candidate resumes, including features such as skills, experience, education, certifications, job role, salary expectations, and project count.

Question 2:  Which column will be used as the target?

Answer: The target variable is "Recruiter Decision", which indicates whether a candidate is hired (Hire) or rejected (Reject).

Task - 2: Basic Data Inspection

Step - 1: Number of rows and columns

In [6]:
df.shape

(1000, 11)

Step - 2: Column names

In [7]:
df.columns

Index(['Resume_ID', 'Name', 'Skills', 'Experience (Years)', 'Education',
       'Certifications', 'Job Role', 'Recruiter Decision',
       'Salary Expectation ($)', 'Projects Count', 'AI Score (0-100)'],
      dtype='object')

Step - 3: Data types of each column

In [8]:
df.dtypes

Resume_ID                  int64
Name                      object
Skills                    object
Experience (Years)         int64
Education                 object
Certifications            object
Job Role                  object
Recruiter Decision        object
Salary Expectation ($)     int64
Projects Count             int64
AI Score (0-100)           int64
dtype: object

Step - 4: Value counts of Recruiter Decision

In [9]:
df['Recruiter Decision'].value_counts()

Recruiter Decision
Hire      812
Reject    188
Name: count, dtype: int64

Step - 5: Summary statistics for numerical columns

In [10]:
df.describe()

,Resume_ID,Experience (Years),Salary Expectation ($),Projects Count,AI Score (0-100)
count,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000
mean,500.500000,4.896000,79994.486000,5.13300,83.950000
std,288.819436,3.112695,23048.472549,3.23137,20.983036
min,1.000000,0.000000,40085.000000,0.00000,15.000000
25%,250.750000,2.000000,60415.750000,2.00000,70.000000
50%,500.500000,5.000000,79834.500000,5.00000,100.000000
75%,750.250000,8.000000,99583.250000,8.00000,100.000000
max,1000.000000,10.000000,119901.000000,10.00000,100.000000

Step - 6: [Q & A]

Question: Explain why data inspection is important before model training.

Answer: The dataset contains multiple columns including both numerical and categorical features. It has 1000 rows and 11 columns.

Data inspection is important before model training to understand the structure, detect inconsistencies, and identify potential issues such as imbalance or incorrect data types.

TASK 3: Data Cleaning and Preprocessing

Step - 1: Drop:

• Resume_ID
    • Name

In [11]:
df = df.drop(['Resume_ID', 'Name'], axis=1)

Step -2: Convert Recruiter Decision:

• Hire → 1

• Reject → 0

In [12]:
df['Recruiter Decision'] = df['Recruiter Decision'].map({
    'Hire': 1,
    'Reject': 0
})

Step - 3: Check for missing values.

• If present, explain how you would handle them.

Ans: Here we have an imbalanced Dataset which means the model might have difficulty in rejecting

In [13]:
df['Recruiter Decision'].value_counts()

Recruiter Decision
1    812
0    188
Name: count, dtype: int64

Above we have some missing values in the dataset so we are now filling those values and checking for missing values again.

Now we don't have any missing values anymore.

In [14]:
df['Certifications'] = df['Certifications'].fillna('')

In [15]:
df.isnull().sum()

Skills                    0
Experience (Years)        0
Education                 0
Certifications            0
Job Role                  0
Recruiter Decision        0
Salary Expectation ($)    0
Projects Count            0
AI Score (0-100)          0
dtype: int64

Step - 4: [Q & A]

Question: Handling missing values

Answer: Data preprocessing was performed to prepare the dataset for machine learning. Unnecessary columns such as Resume_ID and Name were removed as they do not contribute to prediction.

The target variable "Recruiter Decision" was converted into numerical format, where Hire is mapped to 1 and Reject is mapped to 0.

Missing values in the Certifications column were handled by replacing them with empty strings, as it is a text feature.

In [16]:
df = df.drop(['AI Score (0-100)'], axis=1)

TASK - 4: Text Feature Engineering

Step - 1: Combine the Skills, Certifications and Job Role into one column:
combined_text

In [17]:
df['combined_text'] = (
    df['Skills'] + ' ' +
    df['Certifications'] + ' ' +
    df['Job Role']
)

In [18]:
df['combined_text'].head()

0              TensorFlow, NLP, Pytorch  AI Researcher
1    Deep Learning, Machine Learning, Python, SQL G...
2    Ethical Hacking, Cybersecurity, Linux Deep Lea...
3    Python, Pytorch, TensorFlow AWS Certified AI R...
4                  SQL, React, Java  Software Engineer
Name: combined_text, dtype: object

Step - 2: Clean the text:

• Convert to lowercase

• Remove special characters

• Remove extra spaces

In [19]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z ]', '', text)
    text = re.sub(r'\s+', ' ', text)
    return text

df['combined_text'] = df['combined_text'].apply(clean_text)

In [20]:
df['combined_text'].head()

0                 tensorflow nlp pytorch ai researcher
1    deep learning machine learning python sql goog...
2    ethical hacking cybersecurity linux deep learn...
3    python pytorch tensorflow aws certified ai res...
4                     sql react java software engineer
Name: combined_text, dtype: object

Step - 3: [Q & A]

Question: Explain why text cleaning is necessary before vectorization.

Answer: Text cleaning is necessary because raw text may contain noise and inconsistencies, which can negatively impact machine learning models.

This preprocessing ensures consistency and improves the effectiveness of text vectorization.

TASK 5: Convert Text to Numerical Features

Step - 1: Use TfidfVectorizer

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=100)

text_features = tfidf.fit_transform(df['combined_text']).toarray()

In [22]:
text_features.shape

(1000, 27)

Step - 2: [Q & A] Explain:

Question: Why ML models cannot work directly with text.

Answer: Text data cannot be directly used by machine learning models, as they require numerical input. Therefore, the combined_text feature was converted into numerical form using TF-IDF

Question: What TF-IDF represents.

Answer: TF-IDF assigns importance to words based on how frequently they appear in a document and how unique they are across the dataset. This helps in capturing meaningful textual patterns for model training.

TASK 6: Encode Categorical Variables

Step - 1: Encode Education using:

• Label Encoding or One-Hot Encoding

In [23]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Education'] = le.fit_transform(df['Education'])

In [24]:
df['Education'].head()

0    0
1    3
2    3
3    1
4    4
Name: Education, dtype: int64

Step - 2: [Q & A]

Question: Explain the difference between them.

Answer: Machine learning models require numerical input, so encoding is necessary for categorical data.

Label Encoding is efficient for datasets with a limited number of categories.

An alternative method is One-Hot Encoding, which creates separate binary columns for each category.

Task - 7: Feature and Target Separation

Step -1: Separate:

• Features (X)

• Target (y)

In [25]:
y = df['Recruiter Decision']

In [26]:
num_features = df[[
    'Experience (Years)',
    'Salary Expectation ($)',
    'Projects Count',
    'Education'
]]

In [27]:
import numpy as np

X = np.hstack((text_features, num_features))

In [28]:
X.shape
y.shape

(1000,)

Step -2: [Q & A]

Question: Explain why Recruiter Decision should not be included in X.

Answer: The target variable is not included in the feature set to avoid data leakage, as including it would lead to incorrect model learning and unrealistic predictions.

If target is included in features, the model will cheat and learn directly from the answer, leading to incorrect and unrealistic predictions.

TASK 8: Train–Test Split

Step - 1: Split the dataset:

• 80% Training

• 20% Testing

• random_state = 42

In [29]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

Check the shapes after the split.

In [30]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(800, 31)
(200, 31)
(800,)
(200,)

Step - 2: [Q & A] Explain:

Question: Why train–test split is necessary?

Answer: It helps evaluate model performance on unseen data and ensures that the model generalizes well.

Question: What overfitting means?

Answer: When a model performs very well on training data but poorly on unseen test data because it memorizes instead of learning patterns is Overfitting.

TASK 9: Feature Scaling

Step - 1: Apply StandardScaler to numerical features:

• Experience (Years)

• Salary Expectation

• Projects Count

In [31]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [32]:
X_train[:2]

array([[-0.58269311, -0.57935251,  2.13091972,  2.13091972, -0.56453951,
         2.07087438, -0.79289936, -0.53673142, -0.49843336, -0.52736759,
        -0.49843336, -0.467605  , -0.80621193, -0.4797589 , -0.49916468,
        -0.52736759, -0.47387448, -0.49090527,  1.55689639, -0.4813434 ,
        -0.42140018, -0.58269311,  2.07087438, -0.53673142, -0.56357918,
         1.59294052, -0.49713735,  1.63991008, -0.89440139, -0.38750221,
        -0.70578467],
       [-0.58269311, -0.57935251, -0.57697445, -0.57697445, -0.56453951,
        -0.58766074, -0.79289936,  2.30264693, -0.49843336, -0.52736759,
        -0.49843336, -0.467605  , -0.80621193, -0.4797589 , -0.49916468,
        -0.52736759, -0.47387448, -0.49090527, -0.77930121, -0.4813434 ,
         2.98372533, -0.58269311, -0.58766074,  2.30264693, -0.56357918,
         1.89184196, -0.49713735, -0.29794526,  1.2597954 ,  1.48940054,
         1.41156935]])

Step - 2: [Q & A]

Question: Why scaling is important?

Answer: This ensures that all features have a similar scale, preventing features with larger values from dominating the model.

Question: Which models require scaling?

Answer: Scaling is especially important for distance-based models such as K-Nearest Neighbors and Support Vector Machines.

Task - 10: Model Training

Train at least four models:
1. Logistic Regression
2. Random Forest
3. Support Vector Machine
4. K-Nearest Neighbors

Use scaled/unscaled data appropriately.

In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [34]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(),
    "SVM": SVC(),
    "KNN": KNeighborsClassifier()
}

for name, model in models.items():
    model.fit(X_train, y_train)
    pred = model.predict(X_test)

    from sklearn.metrics import accuracy_score
    print(f"{name} Accuracy:", accuracy_score(y_test, pred))

Logistic Regression Accuracy: 0.985
Random Forest Accuracy: 0.945
SVM Accuracy: 0.94
KNN Accuracy: 0.83

Step - 2: [Q & A]

Question: Write a short explanation of how each model works.

Answer: Logistic Regression:

--> Linear model for classification

--> Finds probability of class

 Random Forest:

--> Many decision trees

--> Reduces overfitting

--> Very powerful

SVM:

--> Finds best boundary between classes

--> Works well in high dimensions

KNN:

--> Looks at nearest neighbors

--> Classifies based on similarity

TASK 11: Model Evaluation and Comparison

Step - 1: Print accuracy score for all models.

Step - 2: Display classification report.

In [35]:
from sklearn.metrics import classification_report, accuracy_score

results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    pred = model.predict(X_test)

    acc = accuracy_score(y_test, pred)
    results[name] = acc

    print(f"\n{name}")
    print("Accuracy:", acc)
    print(classification_report(y_test, pred))

Logistic Regression
Accuracy: 0.985
              precision    recall  f1-score   support

           0       0.98      0.96      0.97        46
           1       0.99      0.99      0.99       154

    accuracy                           0.98       200
   macro avg       0.98      0.98      0.98       200
weighted avg       0.98      0.98      0.98       200


Random Forest
Accuracy: 0.955
              precision    recall  f1-score   support

           0       0.97      0.83      0.89        46
           1       0.95      0.99      0.97       154

    accuracy                           0.95       200
   macro avg       0.96      0.91      0.93       200
weighted avg       0.96      0.95      0.95       200


SVM
Accuracy: 0.94
              precision    recall  f1-score   support

           0       1.00      0.74      0.85        46
           1       0.93      1.00      0.96       154

    accuracy                           0.94       200
   macro avg       0.96      0.87      0.91       200
weighted avg       0.94      0.94      0.94       200


KNN
Accuracy: 0.83
              precision    recall  f1-score   support

           0       0.93      0.28      0.43        46
           1       0.82      0.99      0.90       154

    accuracy                           0.83       200
   macro avg       0.88      0.64      0.67       200
weighted avg       0.85      0.83      0.79       200


Step - 3: Create a comparison table:

   Model Name | Accuracy

In [36]:
import pandas as pd

comparison = pd.DataFrame(list(results.items()), columns=['Model', 'Accuracy'])
comparison

                 Model  Accuracy
0  Logistic Regression     0.985
1        Random Forest     0.955
2                  SVM     0.940
3                  KNN     0.830

Step 4: [Q & A]

Question: Which model performed best?

Answer:Logistic Regression

Question: Why might it perform better on this dataset?

Answer: The best model was selected based on overall performance and its ability to correctly classify both hired and rejected candidates.

In [37]:
best_model = max(results, key=results.get)
print("Best Model:", best_model)

Best Model: Logistic Regression

Task - 12 Advanced (Couldn't do)


Task - 13: Build Hiring Prediction Function

Create a function that:

• Takes user input:
• Skills
• Experience
• Education
• Certifications
• Projects Count

• Salary Expectation
• Returns:
• Prediction (Hire or Reject)
• Probability score

This simulates a real AI resume screening tool.

In [41]:
def predict_hiring(skills, experience, education, certifications, projects, salary):

    # Step 1: Combine text
    text = skills + " " + certifications + " " + "job"

    # Step 2: Clean text
    import re
    text = text.lower()
    text = re.sub(r'[^a-zA-Z ]', '', text)
    text = re.sub(r'\s+', ' ', text)

    # Step 3: TF-IDF transform
    text_vec = tfidf.transform([text]).toarray()

    # Step 4: Encode education
    edu_val = le.transform([education])[0]

    # Step 5: Numeric features
    num = [[experience, salary, projects, edu_val]]

    # Step 6: Combine
    import numpy as np
    final_input = np.hstack((text_vec, num))

    # Step 7: Scale
    final_input = scaler.transform(final_input)

    # Step 8: Predict
    actual_best_model = models[best_model]
    pred = actual_best_model.predict(final_input)
    prob = actual_best_model.predict_proba(final_input)

    # Step 9: Output
    result = "Hire" if pred[0] == 1 else "Reject"

    return result, prob[0][1]

Testing the function:

To check whether the model predicts correctly or not?

In [43]:
predict_hiring(
    skills="python machine learning data analysis",
    experience=3,
    education="B.Tech",
    certifications="aws certification",
    projects=5,
    salary=70000
)

('Hire', np.float64(0.9445930068159532))

Conclusion:

• Dataset understanding:

Answer: This project focused on building an AI-based Hiring Prediction System using a resume screening dataset. The dataset contained both structured data such as experience, salary, and project count, as well as unstructured text data including skills, certifications, and job roles.

• Key preprocessing steps:

Answer: Several preprocessing steps were performed, including handling missing values, encoding categorical variables, and transforming text data using TF-IDF. The target variable "Recruiter Decision" was converted into a binary format for classification.

• Best performing model:

Answer: Logistic Regression performed the best based on accuracy and evaluation metrics.

• What you learned?

Answer: This project provided insights into handling real-world datasets, especially combining text and numerical features. It also demonstrated the importance of preprocessing, feature engineering, and model selection.

• How this project connects to real-world HR automation?

Answer: The system simulates real-world HR automation, where AI can assist in screening resumes efficiently and reducing manual effort in hiring processes.